"""Initial migration

Revision ID: a09992de6adb
Revises: c4fdcd099e6a
Create Date: 2025-06-09 19:20:27.886931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a09992de6adb'
down_revision = 'c4fdcd099e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    op.drop_table('post_categories')
    op.drop_table('settings')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('excerpt')
        batch_op.drop_column('author_id')
        batch_op.drop_column('featured_image')
        batch_op.drop_column('status')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.drop_column('full_name')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('featured_image', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('excerpt', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('category_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('published')
        batch_op.drop_column('image')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'category', ['parent_id'], ['id'])
        batch_op.drop_column('updated_at')

    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('site_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('site_description', sa.TEXT(), nullable=True),
    sa.Column('posts_per_page', sa.INTEGER(), nullable=True),
    sa.Column('mail_server', sa.VARCHAR(length=100), nullable=True),
    sa.Column('mail_port', sa.INTEGER(), nullable=True),
    sa.Column('mail_username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('mail_password', sa.VARCHAR(length=100), nullable=True),
    sa.Column('mail_use_tls', sa.BOOLEAN(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('theme', sa.VARCHAR(length=50), nullable=True),
    sa.Column('font_size', sa.VARCHAR(length=20), nullable=True),
    sa.Column('notify_new_comments', sa.BOOLEAN(), nullable=True),
    sa.Column('notify_new_users', sa.BOOLEAN(), nullable=True),
    sa.Column('email_notifications', sa.BOOLEAN(), nullable=True),
    sa.Column('allow_comments', sa.BOOLEAN(), nullable=True),
    sa.Column('require_approval', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_categories',
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'category_id')
    )
    op.create_table('media',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('uploaded_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
