"""Add new settings columns

Revision ID: c4fdcd099e6a
Revises: 
Create Date: 2025-05-08 00:16:13.031369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fdcd099e6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('font_size', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notify_new_comments', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_new_users', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_comments', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('require_approval', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('require_approval')
        batch_op.drop_column('allow_comments')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('notify_new_users')
        batch_op.drop_column('notify_new_comments')
        batch_op.drop_column('font_size')
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
